import type { Plugin } from 'vite';
import { CAPTURE_WORKLET_PATH, CAPTURE_WORKLET_SOURCE } from './src/lib/voiceLive/captureWorkletSource';

/**
 * Serve and emit the native voice capture worklet as a SAME-ORIGIN ASSET.
 *
 * Why this exists: `audioWorklet.addModule()` is a script fetch, so it is
 * governed by the page's `script-src`. The bundle builds the worklet from a
 * string (one source of truth, nothing to go stale), and the obvious way to
 * hand that string over is a `blob:` URL — which production's policy does NOT
 * allow (`script-src 'self'`, no `blob:`). The result was a deployed UI where
 * the native lane could never start capture, while every dev-server run worked:
 * the 2026-09-18 field failure.
 *
 * So the same generated bytes are exposed at `CAPTURE_WORKLET_PATH`:
 *   - dev: a middleware answers the path (the dev server has no CSP at all, but
 *     parity with production means the working path is the same one);
 *   - build: the bytes are emitted into the bundle, and the production server's
 *     `express.static(client/dist)` serves them next to the app.
 *
 * The blob fallback stays in the client for a stale dist or a host that serves
 * neither — it is simply no longer the only way in. No policy is relaxed, and
 * the source is still generated from one place.
 */
export function captureWorkletPlugin(): Plugin {
  const servedPath = CAPTURE_WORKLET_PATH;

  return {
    name: 'voice-capture-worklet',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? '').split('?')[0];
        if (url !== servedPath) {
          next();
          return;
        }
        res.setHeader('Content-Type', 'text/javascript; charset=utf-8');
        res.setHeader('Cache-Control', 'no-store');
        res.end(CAPTURE_WORKLET_SOURCE);
      });
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: servedPath.replace(/^\//, ''),
        source: CAPTURE_WORKLET_SOURCE,
      });
    },
  } as Plugin;
}
