/** Shared Command Code test fixtures. Not a test file — imported by the catalogue and routes suites. */

/** The 54 model ids the installed CLI (v1.23.2) advertises via --list-models. */
export const ADVERTISED_IDS = [
  'deepseek/deepseek-v4-pro',
  'deepseek/deepseek-v4-flash',
  'moonshotai/kimi-k3',
  'moonshotai/kimi-k2.7-code',
  'moonshotai/kimi-k2.7-code-highspeed',
  'moonshotai/kimi-k2.6',
  'moonshotai/kimi-k2.5',
  'zai-org/glm-5.2',
  'zai-org/glm-5.2-fast',
  'zai-org/glm-5.1',
  'zai-org/glm-5',
  'minimaxai/minimax-m3',
  'minimaxai/minimax-m2.7',
  'minimaxai/minimax-m2.5',
  'xiaomi/mimo-v2.5-pro',
  'xiaomi/mimo-v2.5',
  'qwen/qwen3.8-max',
  'qwen/qwen3.7-max',
  'qwen/qwen3.7-plus',
  'qwen/qwen3.7-flash',
  'qwen/qwen3.6-max-preview',
  'qwen/qwen3.6-plus',
  'stepfun/step-3.7-flash',
  'stepfun/step-3.5-flash',
  'tencent/hy3-paid',
  'nvidia/nemotron-3-ultra-550b-a55b',
  'thinkingmachines/inkling',
  'thinkingmachines/inkling-small',
  'poolside/laguna-s-2.1-free',
  'claude-sonnet-5',
  'claude-sonnet-4-6',
  'claude-fable-5',
  'claude-opus-5',
  'claude-opus-4-8',
  'claude-opus-4-7',
  'claude-haiku-4-5',
  'gpt-5.6-sol',
  'gpt-5.6-terra',
  'gpt-5.6-luna',
  'gpt-5.5',
  'gpt-5.4',
  'gpt-5.3-codex',
  'gpt-5.4-mini',
  'google/gemini-3.7-flash',
  'google/gemini-3.6-flash',
  'google/gemini-3.5-flash',
  'google/gemini-3.5-flash-lite',
  'google/gemini-3.1-flash-lite',
  'sakana/fugu-ultra',
  'meta/muse-spark-1.1',
  'meta/muse-spark-1.2',
  'meta/muse-spark-1.2-contributor',
  'xai/grok-4.5',
  'xai/grok-4.6',
] as const;

/** The single source of policy: premium models a GOAT subscription cannot use. */
export const COMMAND_CODE_EXCLUDED_IDS = [
  'claude-sonnet-5',
  'claude-sonnet-4-6',
  'claude-fable-5',
  'claude-opus-5',
  'claude-opus-4-8',
  'claude-opus-4-7',
  'claude-haiku-4-5',
  'gpt-5.6-sol',
  'gpt-5.6-terra',
  'gpt-5.5',
  'gpt-5.4',
  'gpt-5.3-codex',
  'gpt-5.4-mini',
  'google/gemini-3.6-flash',
  'google/gemini-3.5-flash',
  'google/gemini-3.5-flash-lite',
  'google/gemini-3.1-flash-lite',
  'sakana/fugu-ultra',
  'meta/muse-spark-1.1',
] as const;
