/**
 * Test-harness guard: no test process may drive the host service manager.
 *
 * WHY THIS EXISTS (2026-09-15) — production was restarted for real at
 * 2026-09-15T14:27:05Z by an early Vitest run of `restart-drainage.test.ts`. A
 * red-proof command `git stash`-ed `scripts/restart-pi-web-ui.sh` back to its
 * pre-guard revision, whose restart line is a bare `systemctl restart
 * pi-web-ui`; the suite's only interception was `PI_WEB_UI_RESTART_SYSTEMCTL`,
 * an env seam honoured BY THE SCRIPT UNDER TEST, so reverting the
 * implementation removed the guard and its interception together. Two seconds
 * later the unit received SIGTERM, killing the coordination session that was
 * running the suite (it lived inside the unit's control group).
 *
 * Commit d921ac7 fixed that one suite by putting a `systemctl` stub on PATH.
 * This module generalises the fix to the whole test workspace, for the reason
 * that made the incident possible: the guard must not be part of the code under
 * test. It is installed by `tests/setup-env.ts`, so it survives any revision of
 * any script a test might run.
 *
 * Behaviour, deliberately asymmetric:
 *   * state-changing verbs (`restart`, `stop`, `start`, `kill`, …) are REFUSED
 *     loudly with a non-zero exit and are recorded; the host service manager is
 *     never reached, whatever revision of whatever script asked;
 *   * read-only verbs (`status`, `is-active`, `show`, `cat`, …) pass through to
 *     the real binary, so suites may observe the host without mutating it;
 *   * the invocation log is durable beyond the test run, so an attempted
 *     restart leaves a nameable trace instead of vanishing with the temp dir.
 *
 * This is an environment guard, not a policy: it does not stop a human or an
 * agent invoking `systemctl` from a normal shell. See
 * docs/PRODUCTION-STOP-ROBUSTNESS.md for the layers and their trade-offs.
 */
import { chmodSync, existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

/** A shim must not need PATH itself to start: use an absolute interpreter. */
function bashShebang(): string {
  for (const candidate of ['/bin/bash', '/usr/bin/bash']) {
    if (existsSync(candidate)) return `#!${candidate}`;
  }
  return '#!/usr/bin/env bash';
}

/** Directory of the active PATH guard; its presence is the canary suites assert. */
export const SYSTEMCTL_GUARD_MARKER_ENV = 'PI_WEB_UI_SYSTEMCTL_GUARD_DIR';
/** File every guarded invocation is appended to (durable across the test run). */
export const SYSTEMCTL_GUARD_LOG_ENV = 'PI_WEB_UI_SYSTEMCTL_GUARD_LOG';

/**
 * Verbs that change host state. Anything not listed passes through, so the
 * guard stays usable for observation and does not need updating for every new
 * read-only systemctl verb upstream adds.
 */
export const SYSTEMCTL_STATE_CHANGING_VERBS: readonly string[] = [
  'start', 'stop', 'restart', 'try-restart', 'reload', 'reload-or-restart',
  'reload-or-try-restart', 'kill', 'enable', 'disable', 'reenable', 'preset',
  'mask', 'unmask', 'daemon-reload', 'daemon-reexec', 'set-property',
  'reset-failed', 'clean', 'freeze', 'thaw', 'isolate', 'switch-root',
  'rescue', 'emergency', 'default', 'halt', 'poweroff', 'reboot', 'kexec',
  'suspend', 'hibernate', 'hybrid-sleep', 'suspend-then-hibernate',
];

export interface SystemctlGuard {
  /** Directory holding the shim; put this first on a child's PATH. */
  dir: string;
  /** File every invocation is appended to. */
  logPath: string;
  /** Absolute path of the real binary the read-only route execs, if found. */
  realBinary: string | null;
  /** Remove the shim directory. The log is deliberately left behind. */
  uninstall(): void;
}

export interface CreateSystemctlGuardOptions {
  /** Shim directory. Defaults to a fresh temp dir. */
  dir?: string;
  /** Real systemctl to pass read-only verbs to. Defaults to autodetection. */
  realBinary?: string | null;
  /** Invocation log. Defaults to a stable temp path derived from the dir. */
  logPath?: string;
}

const REAL_SYSTEMCTL_CANDIDATES = ['/usr/bin/systemctl', '/bin/systemctl', '/usr/sbin/systemctl'];

function findRealSystemctl(): string | null {
  for (const candidate of REAL_SYSTEMCTL_CANDIDATES) {
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function shimSource(realBinary: string | null, logPath: string): string {
  const verbList = SYSTEMCTL_STATE_CHANGING_VERBS.join('|');
  const passThrough = realBinary
    ? `exec "${realBinary}" "$@"`
    : // No real binary found: fail closed rather than exec `systemctl` off PATH,
      // which would find this shim again and recurse.
      'printf \'systemctl guard: no real systemctl found on this host; refusing.\\n\' >&2\nexit 1';
  return [
    bashShebang(),
    '# Generated by server/tests/systemctl-guard.ts — do not edit by hand.',
    'set -uo pipefail',
    `LOG="\${${SYSTEMCTL_GUARD_LOG_ENV}:-${logPath}}"`,
    '{',
    '  printf \'ts=%s pid=%s ppid=%s tty=%s cwd=%s argv=\' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$$" "$PPID" "$(tty 2>/dev/null || echo none)" "$(pwd 2>/dev/null)"',
    '  printf \'%q \' "$@"',
    '  printf \'\\n\'',
    '} >> "$LOG" 2>/dev/null || true',
    `case "\${1:-}" in`,
    `  ${verbList})`,
    '    printf \'systemctl guard: refusing mutating verb "%s" during a test run.\\n\' "${1:-}" >&2',
    '    printf \'systemctl guard: a test must never drive the host service manager; use a stub seam (PI_WEB_UI_RESTART_SYSTEMCTL) or --dry-run.\\n\' >&2',
    '    printf \'refused %s\\n\' "$*" >> "$LOG" 2>/dev/null || true',
    '    exit 1',
    '    ;;',
    'esac',
    passThrough,
    '',
  ].join('\n');
}

export function createSystemctlGuard(options: CreateSystemctlGuardOptions = {}): SystemctlGuard {
  const dir = options.dir ?? mkdtempSync(path.join(tmpdir(), 'pi-web-ui-systemctl-guard-'));
  const realBinary = options.realBinary === undefined ? findRealSystemctl() : options.realBinary;
  const logPath = options.logPath ?? path.join(tmpdir(), `pi-web-ui-systemctl-guard-${path.basename(dir)}.log`);
  const shimPath = path.join(dir, 'systemctl');
  writeFileSync(shimPath, shimSource(realBinary, logPath));
  chmodSync(shimPath, 0o755);
  return {
    dir,
    logPath,
    realBinary,
    uninstall: () => rmSync(dir, { recursive: true, force: true }),
  };
}

let installed: SystemctlGuard | undefined;

/**
 * Install the process-wide guard: it is prepended to `PATH` so every child a
 * test spawns resolves `systemctl` to the shim. Idempotent per process.
 */
export function installSystemctlGuard(): SystemctlGuard {
  if (installed) return installed;
  installed = createSystemctlGuard({});
  const current = process.env.PATH ?? '';
  process.env.PATH = current ? `${installed.dir}${path.delimiter}${current}` : installed.dir;
  process.env[SYSTEMCTL_GUARD_MARKER_ENV] = installed.dir;
  process.env[SYSTEMCTL_GUARD_LOG_ENV] = installed.logPath;
  process.on('exit', () => installed?.uninstall());
  return installed;
}
